### ISSUE TITLE
`description` が `descreption` になっている

### ISSUE THREAD

**Issue by Hiratake** [Omuretsu/Omuretsu.github.io#5]
タイトルのとおりです。
`description` が `descreption` になっているので、SNS でシェアなどしたときにサイトの説明文が表示されないと思います。
https://github.com/Omuretsu/Omuretsu.github.io/blob/4c9a46070ec163aeae8d254c0fe1530ead1c3556/index.html#L9

**Comment by Omuretsu** [comment]
https://github.com/Omuretsu/Omuretsu.github.io/blob/216e27e1ee8831862c4fd106b60748f38e3309f3/index.html#L13

ここも違いますね...。
修正します。ありがとうございます🙏
